### ISSUE TITLE
[Bug] poetry unable to install pyyaml 

### ISSUE THREAD

**Issue by BuyMyMojo** [LTTLabsOSS/markbench-tests#5]
### Environment

```markdown
- MarkBench Test Version: commit 34ddbefaeda3192926c1f0459f790848e07f859a
- OS: Win11
- GPU: Intel Arc A770
- CPU: amd 5600x
```

### What happened?

When running `poetry install` with a completely fresh python 3.11.5 install it complains about `pyyaml (6.0) not supporting PEP 517 builds` and suggesting to run `pip wheel --use-pep517 "pyyaml (==6.0)"` but after running that nothing changes.

### Relevant log output

```shell
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing pyyaml (6.0)

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  running egg_info
  writing lib\PyYAML.egg-info\PKG-INFO
  writing dependency_links to lib\PyYAML.egg-info\dependency_links.txt
  writing top-level names to lib\PyYAML.egg-info\top_level.txt
  Traceback (most recent call last):
    File "C:\Users\hello\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\hello\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\hello\AppData\Roaming\pypoetry\venv\Lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
      self.run_setup()
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 288, in <module>
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\__init__.py", line 103, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
      dist.run_commands()
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\dist.py", line 989, in run_command
      super().run_command(command)
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
      cmd_obj.run()
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\command\egg_info.py", line 318, in run
      self.find_sources()
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\command\egg_info.py", line 326, in find_sources
      mm.run()
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\command\egg_info.py", line 548, in run
      self.add_defaults()
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\command\egg_info.py", line 586, in add_defaults
      sdist.add_defaults(self)
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\command\sdist.py", line 113, in add_defaults
      super().add_defaults()
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 204, in get_source_files
    File "G:\Temp\tmpss1jx_vg\.venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources


  at ~\AppData\Roaming\pypoetry\venv\Lib\site-packages\poetry\installation\chef.py:147 in _prepare
      143│
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│
      146│             if error is not None:
    → 147│                 raise error from None
      148│
      149│             return path
      150│
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pyyaml (6.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyyaml (==6.0)"'.
```

**Comment by OwenHunter** [comment]
Try change `pyyaml = "6.0"` to `pyyaml = "6.0.1"` in `pyproject.toml` and install again.

**Comment by BuyMyMojo** [comment]
that fixed it 👍
